### ISSUE TITLE
lab files are not fully localized

### ISSUE THREAD

**Issue by bckelly** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.de-de#8]
Many of the lab files are not fully localized. Please review and fix all files in the /Instructions)/Labs/ folder.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Opened files are localized but latest version not on Live. 
Opened https://portal.microsofticm.com/imp/v3/incidents/details/338316385/home

**Comment by chriscarty00** [comment]
issue has been addressed
