### ISSUE TITLE
Missing image file /media/lab03d.png

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.de-de#9]
In instructions document https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.de-de/blob/main/Instructions/Labs/LAB_03d-Manage_Azure_Resources_by_Using_Azure_CLI.md there is a reference to:

../media/lab03d.png

However, this file is missing from the /media directory.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The locfile shown lnLoclization status, waiting for CheckedIn. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtHZXJtYW48L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBBc3NldCBJRDtJcyBJbiBMaXN0O2xhYjEwLnBuZyxsYWIwM2QucG5nPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by chriscarty00** [comment]
Still Inloc

**Comment by stonezy123** [comment]
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.de-de/blob/OLPRODLOC/Instructions/media/lab03d.png 
Locfile check In.
